---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: eks.topic.pageviews
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 12
  kafkaClusterRef:
    name: kafka

---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: pageviews
  namespace: confluent
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 4
  connectClusterRef:
    name: connect
  configs:
    kafka.topic: "eks.topic.pageviews"
    quickstart: "pageviews"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "false"
    max.interval: "500"
    iterations: "10000000"