# An example of ClusterConfig object using an existing VPC:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: shin-eks-sin-cluster
  region: ap-southeast-1

managedNodeGroups:
  - name: managed-ng-public
    instanceType: t3a.large
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
    availabilityZones: ["ap-southeast-1b"]
    volumeSize: 50
    updateConfig:
      maxUnavailable: 1 # or `maxUnavailablePercentage: 75` to specify maxUnavailable as a percentage of total nodes
    labels: {role: worker}

    tags:
      nodegroup-role: worker
      owner_name: shin zhang
      owner_email: szhang@confluent.io
