all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    sasl_protocol: plain

    ### Configuring Role Based Access Control ####
    # To have CP-Ansible configure Components for RBAC and create necessary role bindings, set these mandatory variables:
    # Note: Confluent components will be configured to connect to the "internal" listener automatically
    # DO NOT UPDATE the internal listener
    # Note: It is recommended to create an additional listener for external clients, but the interbroker listener would also work
    # Note: An authentication mode must be selected on all listeners, for example (ssl_enabled=false and ssl_mutual_auth_enabled=false) or sasl_protocol=none is not supported.
    rbac_enabled: true
    #
    # LDAP Users
    # Note: Below users must already exist in your LDAP environment. 
    mds_super_user: mds
    mds_super_user_password: mds
    kafka_broker_ldap_user: kafka_broker
    kafka_broker_ldap_password: kafka_broker
    schema_registry_ldap_user: schema_registry
    schema_registry_ldap_password: schema_registry
    kafka_connect_ldap_user: connect_worker
    kafka_connect_ldap_password: connect_worker
    ksql_ldap_user: ksql
    ksql_ldap_password: ksql
    kafka_rest_ldap_user: kafka_rest
    kafka_rest_ldap_password: kafka_rest
    control_center_ldap_user: control_center
    control_center_ldap_password: control_center
    # Allow the playbooks to configure additional users as system admins on the platform, set the list below
    rbac_component_additional_system_admins:
      - superuser

    kafka_broker_custom_listeners:
      client_listener:
        name: CLIENT
        port: 9093

zookeeper:
  hosts: {}
kafka_broker:
  vars:
    kafka_broker_custom_properties:
      password.encoder.secret: encoder-secret

      # Configure MDS to talk to LDAP
      ldap.java.naming.factory.initial: com.sun.jndi.ldap.LdapCtxFactory
      ldap.com.sun.jndi.ldap.read.timeout: 3000
      ldap.java.naming.provider.url: ldap://bastion-0.shin.ps.confluent.io:389
      # ldap.ssl.truststore.location: /var/ldap_certs/ldap_truststore.jks
      # ldap.ssl.truststore.password: passwd
      # ldap.java.naiming.security.protocol: SSL

      # Authentication to LDAP
      ldap.java.naming.security.principal: cn=mds,ou=users,dc=shin,dc=ps,dc=confluent,dc=io
      ldap.java.naming.security.credentials: mds
      ldap.java.naming.security.authentication: simple

      # Locate LDAP users and groups
      ldap.user.search.base: ou=users,dc=shin,dc=ps,dc=confluent,dc=io
      ldap.group.search.base: ou=groups,dc=shin,dc=ps,dc=confluent,dc=io
      ldap.user.name.attribute: cn
      ldap.user.memberof.attribute.pattern: cn=(.*),ou=users,dc=shin,dc=ps,dc=confluent,dc=io
      ldap.group.name.attribute: cn
      ldap.group.member.attribute.pattern: cn=(.*),ou=users,dc=shin,dc=ps,dc=confluent,dc=io
      ldap.user.object.class: inetOrgPerson

  hosts: {}
control_center:
  hosts: {}
schema_registry:
  vars:
    schema_registry_custom_properties:
      resource.extension.class: io.confluent.schema.exporter.SchemaExporterResourceExtension
      kafkastore.update.handlers: io.confluent.schema.exporter.storage.SchemaExporterUpdateHandler
      password.encoder.secret: encoder-secret
  hosts: {}
kafka_connect:
  vars:
    kafka_connect_confluent_hub_plugins:
    - confluentinc/kafka-connect-http:1.6.1
    - confluentinc/kafka-connect-datagen:0.6.0
    - confluentinc/kafka-connect-oracle-cdc:2.2.2
  hosts: {}
ksql:
  hosts: {}
kafka_rest:
  hosts: {}
