# An example of ClusterConfig object using an existing VPC:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: shin-eks-tky-cluster
  region: ap-northeast-1

managedNodeGroups:
  - name: managed-ng-public
    instanceType: t3a.large
    minSize: 2
    desiredCapacity: 2
    maxSize: 4
    availabilityZones: ["ap-northeast-1a"]
    volumeSize: 50
    updateConfig:
      maxUnavailable: 3 # or `maxUnavailablePercentage: 75` to specify maxUnavailable as a percentage of total nodes
    labels: {role: worker}

    tags:
      nodegroup-role: worker
      owner_name: shin zhang
      owner_email: szhang@confluent.io
