# An example of ClusterConfig object using an existing VPC:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: shin-eks-cluster
  region: ap-southeast-2

vpc:
  id: "vpc-eb1daf8c"
  subnets:
    public:
      ap-southeast-2a:
        id: "subnet-86a6cacf"
      ap-southeast-2b:
        id: "subnet-05017362"
      ap-southeast-2c:
        id: "subnet-eb48bab3"

managedNodeGroups:
  - name: managed-ng-public
    instanceType: t3a.large
    minSize: 4
    desiredCapacity: 4
    maxSize: 8
    availabilityZones: ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c"]
    volumeSize: 50
    labels: {role: worker}
    iam:
      withAddonPolicies:
        externalDNS: true
    tags:
      nodegroup-role: worker
      owner_name: shin zhang
      owner_email: szhang@confluent.io
